name: Build & Test

on:
  push:
    branches: ['*']
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: quantconnect/lean:foundation
    steps:
      - uses: actions/checkout@v2

      - name: Checkout Lean Same Branch
        id: lean-same-branch
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: ${{ github.ref }}
          repository: QuantConnect/Lean
          path: Lean

      - name: Checkout Lean Master
        if: steps.lean-same-branch.outcome != 'success'
        uses: actions/checkout@v2
        with:
          repository: QuantConnect/Lean
          path: Lean

      - name: Move Lean
        run: mv Lean ../Lean

      - name: Build
        run: dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 QuantConnect.FTXBrokerage.sln

      - name: Run Tests
        run: dotnet test ./QuantConnect.FTXBrokerage.Tests/bin/Release/QuantConnect.FTXBrokerage.Tests.dll
        env:
          ftx-api-key: ${{ secrets.FTX_API_KEY }}
          ftx-api-secret: ${{ secrets.FTX_API_SECRET }}
          data-folder: ../../../../Lean/Data/